
import { GoogleGenAI, Type } from "@google/genai";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  async generateWaldoImage(base64Image: string, scenery: string): Promise<string> {
    const prompt = `
      Create a high-detail, dense, and complex "Where's Wally" (Where's Waldo) style cartoon illustration.
      
      THE TARGET: Convert the person in the provided photo into a distinct cartoon character. 
      Keep their recognizable features such as hair color, hairstyle, and facial structure (translated to cartoon style). 
      IMPORTANT: Dress them in a bright, identifiable outfit (like red and white stripes or another distinct pattern) so they can eventually be found.
      
      THE SCENE: Place this character within a massive, crowded, and busy scene set in: ${scenery}.
      
      THE CROWD: Fill the entire image with hundreds of other unique, colorful, and diverse cartoon characters performing various funny actions. 
      Add complex backgrounds, vehicles, buildings, or elements relevant to the ${scenery} theme.
      
      STYLE: Traditional 2D hand-drawn cartoon style with clean lines and vibrant colors. 
      The character should be integrated naturally but hidden in the chaos.
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Image.split(',')[1],
                mimeType: 'image/png',
              },
            },
            {
              text: prompt,
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let imageUrl = '';
      if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
            break;
          }
        }
      }

      if (!imageUrl) {
        throw new Error("No image was generated by the model.");
      }

      return imageUrl;
    } catch (error) {
      console.error("Gemini Generation Error:", error);
      throw error;
    }
  }

  async locateTarget(targetBase64: string, generatedBase64: string): Promise<[number, number, number, number] | null> {
    const prompt = "The first image is a reference photo of a person. The second image is a dense 'Where's Waldo' style illustration where that person has been drawn as a cartoon character. Find the cartoon version of the person in the illustration and return its bounding box coordinates [ymin, xmin, ymax, xmax] as normalized values between 0 and 1000.";

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: {
          parts: [
            {
              inlineData: {
                data: targetBase64.split(',')[1],
                mimeType: 'image/png',
              },
            },
            {
              inlineData: {
                data: generatedBase64.split(',')[1],
                mimeType: 'image/png',
              },
            },
            { text: prompt }
          ]
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              box_2d: {
                type: Type.ARRAY,
                items: { type: Type.NUMBER },
                description: "The normalized [ymin, xmin, ymax, xmax] coordinates (0-1000)."
              }
            },
            required: ["box_2d"]
          }
        }
      });

      const result = JSON.parse(response.text || '{}');
      if (result.box_2d && result.box_2d.length === 4) {
        return result.box_2d;
      }
      return null;
    } catch (error) {
      console.error("Locate Target Error:", error);
      return null;
    }
  }
}

export const geminiService = new GeminiService();
