
import { GoogleGenAI, Type } from "@google/genai";

export interface GenerationResult {
  imageUrl: string;
  questItems: string[];
}

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  async generateWaldoImage(base64Image: string, scenery: string): Promise<GenerationResult> {
    const prompt = `
      Create a high-detail, dense, and complex "Where's Wally" (Where's Waldo) style cartoon illustration.
      
      THE TARGET: Convert the person in the provided photo into a distinct cartoon character. 
      Keep their hair color, hairstyle, and facial structure (translated to cartoon style). 
      Dress them in a very distinct, bright outfit (e.g. bold patterns, unique hat) so they can be identified.
      
      THE SCENE: Place this character within a massive, crowded scene set in: ${scenery}.
      
      THE CROWD: Fill the entire image with hundreds of other unique, colorful, and diverse cartoon characters performing various funny actions. 
      Add complex backgrounds, vehicles, and buildings relevant to the ${scenery} theme.
      
      SPECIAL THEMED CHARACTERS: Include at least 5 unique "easter egg" characters or objects specifically related to the "${scenery}" theme (e.g., if it's Space, include a space-dog, a floating pizza, a specific alien thief, etc.).
      
      STYLE: Traditional 2D hand-drawn cartoon style with clean lines and vibrant colors. 
      
      OUTPUT: In addition to the image, provide a JSON list of 5 specific themed items or characters you added to the scene for the user to find (not including the main target person).
      Format the text part of your response as a valid JSON array of strings, like this: ["a blue cat with a jetpack", "a spilled ice cream cone", ...].
    `;

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: base64Image.split(',')[1],
                mimeType: 'image/png',
              },
            },
            {
              text: prompt,
            },
          ],
        },
        config: {
          imageConfig: {
            aspectRatio: "16:9"
          }
        }
      });

      let imageUrl = '';
      let questItems: string[] = [];

      if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          } else if (part.text) {
            try {
              // Extract JSON from the text response if it's wrapped in markdown or just raw
              const jsonMatch = part.text.match(/\[.*\]/s);
              if (jsonMatch) {
                questItems = JSON.parse(jsonMatch[0]);
              }
            } catch (e) {
              console.error("Failed to parse quest items JSON", e);
            }
          }
        }
      }

      if (!imageUrl) {
        throw new Error("No image was generated by the model.");
      }

      // Fallback items if JSON parsing fails
      if (questItems.length === 0) {
        questItems = ["A hidden treasure", "A funny character", "Something out of place", "A themed animal", "A secret symbol"];
      }

      return { imageUrl, questItems };
    } catch (error) {
      console.error("Gemini Generation Error:", error);
      throw error;
    }
  }

  async locateTarget(targetBase64: string, generatedBase64: string): Promise<[number, number, number, number] | null> {
    const prompt = "The first image is a reference photo. The second is a dense illustration. Find the person from the first photo drawn as a cartoon in the second. Return ONLY the bounding box [ymin, xmin, ymax, xmax] as normalized values 0-1000.";

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: {
          parts: [
            {
              inlineData: {
                data: targetBase64.split(',')[1],
                mimeType: 'image/png',
              },
            },
            {
              inlineData: {
                data: generatedBase64.split(',')[1],
                mimeType: 'image/png',
              },
            },
            { text: prompt }
          ]
        },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              box_2d: {
                type: Type.ARRAY,
                items: { type: Type.NUMBER },
              }
            },
            required: ["box_2d"]
          }
        }
      });

      const result = JSON.parse(response.text || '{}');
      if (result.box_2d && result.box_2d.length === 4) {
        return result.box_2d;
      }
      return null;
    } catch (error) {
      console.error("Locate Target Error:", error);
      return null;
    }
  }
}

export const geminiService = new GeminiService();
